services:
  fbmstore-web:
    build: ./fbmstore-web
    container_name: fbmstore-web
    networks:
      - saas-network
    restart: always

  nginx-edge:
    image: nginx:alpine
    container_name: nginx-edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-edge.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fbmstore-web
    networks:
      - saas-network
    restart: always

networks:
  saas-network:
    external: true